version: "3.9"

volumes:
  gem_cache:

services:
  app:
    build: .
    volumes:
      - .:/var/app
      - gem_cache:/usr/local/bundle/gems
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    entrypoint: entrypoint.sh

  test:
    build: .
    volumes:
      - .:/var/app
      - gem_cache:/usr/local/bundle/gems
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true
    entrypoint: entrypoint.sh
    command: ['rspec', '-fdoc']
